# Generated by Django 5.1.4 on 2026-01-05 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Dépôt'), ('transfer', 'Transfert'), ('withdrawal', 'Retrait'), ('fee', 'Commission')], max_length=20, verbose_name='Type de transaction')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Montant de la transaction en FCFA', max_digits=12, verbose_name='Montant')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complétée'), ('failed', 'Échouée')], default='completed', max_length=20, verbose_name='Statut')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('reference', models.CharField(help_text='Référence unique de la transaction', max_length=100, unique=True, verbose_name='Référence')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('receiver_account', models.ForeignKey(blank=True, help_text='NULL pour les retraits', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_transactions', to='core.virtualaccount', verbose_name='Compte destinataire')),
                ('sender_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_transactions', to='core.virtualaccount', verbose_name='Compte émetteur')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='transaction_created_300c15_idx'), models.Index(fields=['sender_account', '-created_at'], name='transaction_sender__b66812_idx'), models.Index(fields=['receiver_account', '-created_at'], name='transaction_receive_22a821_idx'), models.Index(fields=['transaction_type'], name='transaction_transac_09d7ec_idx'), models.Index(fields=['reference'], name='transaction_referen_923a88_idx')],
            },
        ),
    ]
